Feat/direct pay
uc-cdis/BMH-admin-portal pull request #50
Opened 2023-02-09 16:59 UTC by urvi-occ

### New Features
Introducing direct pay feature in the BMH Admin portal. The feature includes a new form to submit information to apply for direct pay with OCC as reseller.

-> New tab is introduced in form to submit information for direct pay
-> On Homepage, new table for OCC Direct Pay is created where the requests for Direct Pay are shown. The difference in this table is the field of strides credits is replaced by compute purchased and Sift and hard limits are not editable.

2023-02-21 17:16 UTC, tianj7 commented on bmh_admin_portal_backend/lambda/lambda_authorizer/lambda_authorizer.py
> -        policy.allowMethod("PUT", "/workspaces/*/total-usage")
Just curious, why are we removing access to the "total-usage" endpoint for application type request?

2023-02-21 17:39 UTC, urvi-occ commented on bmh_admin_portal_backend/lambda/lambda_authorizer/lambda_authorizer.py
> +        policy.allowMethod("PUT", "/workspaces/*/direct-pay-limit")
No worries :)

2023-02-21 18:09 UTC, urvi-occ commented on bmh_admin_portal_backend/lambda/lambda_authorizer/lambda_authorizer.py
> -        policy.allowMethod("PUT", "/workspaces/*/total-usage")
@nss10 would be a better person to answer it but as per sai and I discussed, occ would not be using that call

2023-02-21 18:49 UTC, nss10 commented on bmh_admin_portal_backend/lambda/lambda_authorizer/lambda_authorizer.py
> -        policy.allowMethod("PUT", "/workspaces/*/total-usage")
Yes. OCC wouldn't be updating `total-usage`. This happened due to a confusion in the language between the terms `total-usage` and `compute-purchased`. OCC would require access to update the `direct-pay-limit` AKA `compute-purchased` and would not have access to updating `total-usage`.

2023-02-21 18:59 UTC, urvi-occ commented
@nss10 I have added the code for suggested changes

-> changed axios to fetch
-> made value of data variable more readable

2023-02-21 18:59 UTC, urvi-occ commented on bmh_admin_portal_ui/src/components/request-workspace/direct-pay-form.js
> +    var data = '{\n    "queryStringParameters": \n    {\n        "method": "handleRequest",\n        "brh_data" : {\n            "AGBillingID": "' + billingID +'",\n            "Email": "' + email +
Yes, done

2023-02-21 19:00 UTC, urvi-occ commented on bmh_admin_portal_ui/src/components/request-workspace/direct-pay-form.js
> +  var axios = require('axios');
That was a good suggestion, I just made a commit to change axios to fetch

2023-02-21 19:00 UTC, urvi-occ commented on bmh_admin_portal_ui/src/components/request-workspace/direct-pay-form.js
> +  }
Replaced ✔️

2023-02-23 21:19 UTC, nss10 commented on bmh_admin_portal_backend/lambda/workspaces_api_resource/workspaces_api_resource_handler.py
> +        root_email = f"root_{workspace_request_id}@{occ_email_domain}"
This variable is not fetched from the `environment variables`

2023-02-24 20:17 UTC, urvi-occ commented on bmh_admin_portal_backend/lambda/workspaces_api_resource/workspaces_api_resource_handler.py
> +        root_email = f"root_{workspace_request_id}@{occ_email_domain}"
Good observation @nss10 and I am sorry I missed it. code added for fetching the variable from the env variables.

2023-03-07 23:01 UTC, nss10 requested changes
Great work on the new changes. Thank you :) . I've left some comments on the code with some suggestions. Please take a look.

2023-03-07 23:01 UTC, nss10 commented on bmh_admin_portal_ui/src/components/request-workspace/direct-pay-form.js
> +  const form = event.currentTarget;
I see this variable is declared but never used. Do we need this one?

2023-03-07 23:01 UTC, nss10 requested changes
Great work on the new changes. Thank you :) . I've left some comments on the code with some suggestions. Please take a look.

2023-03-09 00:19 UTC, urvi-occ commented on bmh_admin_portal_ui/src/components/request-workspace/direct-pay-form.js
> +   updateFormData({
Changed

2023-03-09 00:21 UTC, urvi-occ commented on bmh_admin_portal_ui/src/components/request-workspace/direct-pay-form.js
> +  }
I can't use `requestWorkspace` as I need the request UUID from the response and the response to this function is empty so I can't change it :)

2023-03-09 00:21 UTC, urvi-occ commented on bmh_admin_portal_ui/src/components/request-workspace/direct-pay-form.js
> +  }
I can't use `requestWorkspace` as I need the request UUID from the response and the response to this function is empty so I can't use the original function.

2023-03-09 00:22 UTC, urvi-occ commented on bmh_admin_portal_ui/src/components/request-workspace/direct-pay-form.js
> +  })
I can't use the function as I am not getting the required response from the API

2023-03-09 00:27 UTC, urvi-occ commented on bmh_admin_portal_ui/src/components/request-workspace/direct-pay-form.js
> +const { updateRedirectHome } = props
removed all unused variables and added `updateRedirectHome`

2023-03-09 00:27 UTC, urvi-occ commented on bmh_admin_portal_ui/src/components/request-workspace/direct-pay-form.js
> +  const form = event.currentTarget;
removed

2023-03-09 00:28 UTC, urvi-occ commented
Hey @nss10 Thank you so much for all your comments, I have made almost all changes and I responded to comments to the changes which I couldn't make. Let me know what you think

2023-03-13 23:45 UTC, nss10 commented on bmh_admin_portal_ui/src/components/request-workspace/direct-pay-form.js
> +  }
I see that this is implemented now. Resolving the thread

2023-03-13 23:49 UTC, nss10 commented on bmh_admin_portal_ui/src/util/api.jsx
> +}
Can we add a parameter `method` instead of hardcoding `POST` method?

2023-03-14 00:35 UTC, nss10 commented on bmh_admin_portal_ui/src/components/request-workspace/direct-pay-form.js
> +  }
Resolving since this is solved based on the above discussions and new changes

2023-03-14 00:36 UTC, nss10 commented on bmh_admin_portal_ui/src/components/request-workspace/direct-pay-form.js
> +  })
Resolving based on the new changes

2023-03-15 15:59 UTC, nss10 commented on bmh_admin_portal_ui/src/components/request-workspace/direct-pay-form.js
> +    requestWorkspace
`callExternalURL` was not imported here, but is used in `line 73` and `line 151`.  I see the error [here](https://github.com/occ-data/BMH-admin-portal/actions/runs/4411066875/jobs/7729210529).

2023-03-15 16:27 UTC, urvi-occ commented on bmh_admin_portal_ui/src/components/request-workspace/direct-pay-form.js
> +    requestWorkspace
Thanks for this. I have added the code for it

2023-03-15 16:54 UTC, nss10 commented on bmh_admin_portal_backend/lambdas/lambda_authorizer/lambda_authorizer.py
> -        policy.allowMethod("PUT", "/workspaces/*/total-usage")
These access privileges are for `client-credentials` grant type. This policy was added  initially when there was an assumption that OCC would be tracking the usage of the users and updates the cost. But is being corrected since this is done by us [here](https://github.com/uc-cdis/BMH-admin-portal/blob/2b8eaea14a2c6e8c71762532ef1a0dc3e540ba51/bmh_workspace/lambdas/parse_cost_and_usage_lambda/parse_cost_and_usage_lambda.py#L55-L66)

2023-03-15 20:44 UTC, Avantol13 commented on bmh_admin_portal_backend/lambdas/workspaces_api_resource/workspaces_api_resource_handler.py
> +    if occ_email_domain is None:
If you wanted more flexibility to catch empty strings here, you could simply `if occ_email_domain:`

2023-03-15 20:48 UTC, Avantol13 commented on bmh_admin_portal_backend/lambdas/workspaces_api_resource/workspaces_api_resource_handler.py
> +        return create_response(status_code=200, body={"message": workspace_request_id})
is the "message" in the response being interpreted semantically by the receiver? Are they expecting this to be a workspace request ID? If so, we shouldn't embed that in an existing "message" key. You should have an explicit storage for this information and perhaps only include it when available (like a new "workspace_request_id" field).

Having "message" be a simple message in some cases but contain parseable, important information in others seems a little dangerous / unintuitive.

2023-03-15 20:49 UTC, Avantol13 commented on bmh_admin_portal_backend/lambdas/workspaces_api_resource/workspaces_api_resource_handler.py
> +        return create_response(status_code=200, body={"message": workspace_request_id})
I understand that requires the client to change, but they should be explicit about when they're checking for this request ID

2023-03-15 20:52 UTC, Avantol13 commented on bmh_admin_portal_backend/lambdas/workspaces_api_resource/workspaces_api_resource_handler.py
> +    assert "workspace_id" in path_params
we tend to not use `assert` outside of tests. It's not necessarily a rule, but the pattern we typically employ in situations like this is an explicit check and raising of an error with useful message. That gives more flexibility in what information ends up in the trace.

Example:

```
if "workspace_id" not in path_params:
  raise UserError(f"Expected 'workspace_id' in provided path parameters but was not found. Provided: {path_params}")
```

2023-03-15 20:57 UTC, Avantol13 commented on bmh_admin_portal_backend/lambdas/workspaces_api_resource/workspaces_api_resource_handler.py
> +    direct_pay_limit = round(decimal.Decimal(body["direct_pay_limit"]), 2)
what if `direct_pay_limit` fails to cast to a Decimal? I think you need to protect against that and raise a useful error

```
>>> round(decimal.Decimal("foobar"), 2)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
decimal.InvalidOperation: [<class 'decimal.ConversionSyntax'>]
```

2023-03-15 20:57 UTC, Avantol13 commented on bmh_admin_portal_backend/lambdas/workspaces_api_resource/workspaces_api_resource_handler.py
> +        raise ValueError("Direct pay limit must be a postive number")
```suggestion
        raise ValueError("Direct pay limit must be a positive number")
```

2023-03-15 20:58 UTC, Avantol13 commented on bmh_admin_portal_backend/lambdas/workspaces_api_resource/workspaces_api_resource_handler.py
> +            "Could Not find record with exsisitng workspace_id and user" + str(e)
```suggestion
            "Could not find record with existing workspace_id and user. Error: " + str(e)
```

2023-03-15 20:58 UTC, Avantol13 commented on bmh_admin_portal_backend/lambdas/workspaces_api_resource/workspaces_api_resource_handler.py
> +            "The new direct pay amount is less than the soft limit or hard limit "
```suggestion
            "The new direct pay amount is less than the soft limit or hard limit"
```

2023-03-15 20:58 UTC, Avantol13 commented on bmh_admin_portal_backend/lambdas/workspaces_api_resource/workspaces_api_resource_handler.py
> +            "The new direct pay amount is less than the old direct pay amount "
```suggestion
            "The new direct pay amount is less than the old direct pay amount"
```

2023-03-15 21:00 UTC, Avantol13 commented on bmh_admin_portal_backend/lambdas/workspaces_api_resource/workspaces_api_resource_handler.py
> +                ":direct": round(decimal.Decimal(body["direct_pay_limit"]), 2)
you already converted this earlier and stored in `direct_pay_limit`, you can use that here

https://github.com/uc-cdis/BMH-admin-portal/pull/50/files#diff-988707a056a08fe71dcbcb0e38f0934cb79ed2d9032fffbaa65d509d7e3649c5R758

2023-03-15 21:00 UTC, urvi-occ commented on bmh_admin_portal_backend/lambdas/workspaces_api_resource/workspaces_api_resource_handler.py
> +    if occ_email_domain is None:
We have just followed the template for `email_domain` and made the same for `occ_email_domain` Do you want me to change for both?

2023-03-15 21:01 UTC, Avantol13 commented on bmh_admin_portal_backend/lambdas/workspaces_api_resource/workspaces_api_resource_handler.py
> +    if occ_email_domain is None:
It depends on if that simplification makes sense for your use case. Is empty string the same issue as None? If so, I'd change it for both, yes.

2023-03-15 21:13 UTC, urvi-occ commented on bmh_admin_portal_backend/lambdas/workspaces_api_resource/workspaces_api_resource_handler.py
> +        return create_response(status_code=200, body={"message": workspace_request_id})
we can work on having some other key than `message` do you have any suggestions?

2023-03-15 21:14 UTC, urvi-occ commented on bmh_admin_portal_backend/lambdas/workspaces_api_resource/workspaces_api_resource_handler.py
> +    assert "workspace_id" in path_params
This should be taken care of by either @jawadqur or @nss10 as this is the existing functionality in BRH admin portal

2023-03-15 21:29 UTC, Avantol13 commented on bmh_admin_portal_backend/lambdas/workspaces_api_resource/workspaces_api_resource_handler.py
> +        return create_response(status_code=200, body={"message": workspace_request_id})
I'm not super familiar with this code base or immersed in the use cases here, so your opinion is better than my guess in my comment above

2023-03-15 21:30 UTC, Avantol13 commented on bmh_admin_portal_backend/lambdas/workspaces_api_resource/workspaces_api_resource_handler.py
> +    assert "workspace_id" in path_params
Yeah, I'm providing a high-level review of coding patterns and rough suggestions from the Gen3 side, so take all these comments with a grain of salt.

2023-03-15 21:30 UTC, urvi-occ commented on bmh_admin_portal_backend/lambdas/workspaces_api_resource/workspaces_api_resource_handler.py
> +                ":direct": round(decimal.Decimal(body["direct_pay_limit"]), 2)
Thanks for the suggestion, changes are made according to this :)

2023-03-15 21:31 UTC, urvi-occ commented on bmh_admin_portal_backend/lambdas/workspaces_api_resource/workspaces_api_resource_handler.py
> +            "The new direct pay amount is less than the old direct pay amount "
Thanks for the suggestion, changes are made according to this :)

2023-03-15 21:31 UTC, urvi-occ commented on bmh_admin_portal_backend/lambdas/workspaces_api_resource/workspaces_api_resource_handler.py
> +            "The new direct pay amount is less than the soft limit or hard limit "
Thanks for the suggestion, changes are made according to this :)

2023-03-15 21:31 UTC, urvi-occ commented on bmh_admin_portal_backend/lambdas/workspaces_api_resource/workspaces_api_resource_handler.py
> +            "Could Not find record with exsisitng workspace_id and user" + str(e)
Thanks for the suggestion, changes are made according to this :)

2023-03-15 21:31 UTC, urvi-occ commented on bmh_admin_portal_backend/lambdas/workspaces_api_resource/workspaces_api_resource_handler.py
> +        raise ValueError("Direct pay limit must be a postive number")
Thanks for the suggestion, changes are made according to this :)

2023-03-15 21:31 UTC, urvi-occ commented on bmh_admin_portal_backend/lambdas/workspaces_api_resource/workspaces_api_resource_handler.py
> +    direct_pay_limit = round(decimal.Decimal(body["direct_pay_limit"]), 2)
Thanks for the suggestion, I have added a try-expect block around this

2023-03-15 21:34 UTC, urvi-occ commented on bmh_admin_portal_backend/lambdas/workspaces_api_resource/workspaces_api_resource_handler.py
> +        return create_response(status_code=200, body={"message": workspace_request_id})
I am wondering, security-wise, if is it okay that I change the key `message` to `workspace-request-id`? I just want to make sure that explicitly calling it the request-id is not a security issue

2023-03-15 21:38 UTC, urvi-occ commented on bmh_admin_portal_backend/lambdas/workspaces_api_resource/workspaces_api_resource_handler.py
> +    assert "workspace_id" in path_params
I see it and your input is valuable, I just wanted to make sure that it reaches to right person :)

2023-03-15 21:40 UTC, urvi-occ commented on bmh_admin_portal_backend/lambdas/workspaces_api_resource/workspaces_api_resource_handler.py
> +    if occ_email_domain is None:
I made changes to both :)

2023-03-16 17:48 UTC, tianj7 commented on bmh_admin_portal_backend/lambdas/workspaces_api_resource/workspaces_api_resource_handler.py
> +    if email_domain:
Hi Urvi, just wondering why the "is None" is removed here? Looks like the code will throw the error if email_domain is successfully populated?

2023-03-16 17:49 UTC, tianj7 commented on bmh_admin_portal_backend/lambdas/workspaces_api_resource/workspaces_api_resource_handler.py
> +    if occ_email_domain:
Same issue as above, we should be checking if occ_email_domain "is None" then throw the value error?

2023-03-16 20:23 UTC, nss10 commented on bmh_admin_portal_backend/lambdas/workspaces_api_resource/workspaces_api_resource_handler.py
> +        return create_response(status_code=200, body={"message": workspace_request_id})
I don't think having a key with that name by  itself is going to be causing any troubles in terms of security. If we're going ahead with this, then we need to make sure we change the logic [here](https://github.com/uc-cdis/BMH-admin-portal/blob/3b882fd7e9cb326ebdd1ba2cde87236acb0a6998/bmh_admin_portal_ui/src/components/request-workspace/direct-pay-form.js#L118-L118)

2023-03-16 20:24 UTC, nss10 commented on bmh_admin_portal_backend/lambdas/workspaces_api_resource/workspaces_api_resource_handler.py
> +    if email_domain:
I think the right condition you're looking for is 

```suggestion
    if not email_domain:
```

2023-03-16 20:30 UTC, nss10 commented on bmh_admin_portal_backend/lambdas/workspaces_api_resource/workspaces_api_resource_handler.py
> +    if occ_email_domain:
```suggestion
    if not occ_email_domain:
```

2023-03-21 23:31 UTC, nss10 commented on bmh_admin_portal_ui/src/components/request-workspace/direct-pay-form.js
> +    workspace_use: " ",
We need another key called `ecs:true` in this intial form data, which resolves the workspace provisioning issue we faced earlier. @jawadqur , can you please confirm on this?

2023-03-22 21:09 UTC, urvi-occ commented on bmh_admin_portal_backend/lambdas/workspaces_api_resource/workspaces_api_resource_handler.py
> +        return create_response(status_code=200, body={"message": workspace_request_id})
I have made the update for this :) please let me know if this make sense @Avantol13 @nss10

2023-04-03 15:41 UTC, jawadqur commented on bmh_admin_portal_ui/src/components/request-workspace/direct-pay-form.js
> +    workspace_use: " ",
Yes, we do!

2023-04-10 14:59 UTC, urvi-occ commented
Closing this PR to make changes for Test cases

2023-04-10 14:59 UTC, closed without merging